LR:
  train_file: [ '/data/nfs/qiuchen/hyf/datasets/LR/LR_new_json/LR_train.json' ]
  test_file: [ '/data/nfs/qiuchen/hyf/datasets/LR/LR_new_json/LR_test.json' ]
  val_file: [ '/data/nfs/qiuchen/hyf/datasets/LR/LR_new_json/LR_val.json' ]
  answer_list_test: '/data/nfs/qiuchen/hyf/datasets/LR/LR_new_json/answers_list_test.json'
  answer_list_val: '/data/nfs/qiuchen/hyf/datasets/LR/LR_new_json/answers_list_val.json'
  vqa_root: '/data/nfs/qiuchen/hyf/datasets/LR/Images_LR/'

VRS:
  train_file: [ '/data/nfs/qiuchen/hyf/datasets/VRSBench/VRS_VQA_train.json' ]
  test_file: [ '/data/nfs/qiuchen/hyf/datasets/VRSBench/VRS_VQA_test.json' ]
  answer_list: '/data/nfs/qiuchen/hyf/datasets/VRSBench/answers_list_test.json'
  vqa_root: '/data/nfs/qiuchen/hyf/datasets/VRSBench/rs_images'
  
image_res: 384      # 480  384  256
batch_size_train: 8
batch_size_test: 4


bert_config: 'configs/config_bert.json'

# optimizer
init_lr: 2e-5
weight_decay: 0.05
#min_lr: 0
min_lr: 1e-8
max_epoch: 20
